export { default as AboutPage } from './AboutPage'
export { default as BrowserProjectsPage } from './BrowserProjectsPage'
export { default as ContactPage } from './ContactPage'
export { default as HomePage } from './HomePage'
export { default as NotFoundPage } from './NotFoundPage'
export { default as ProjectsPage } from './ProjectsPage'